// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTTVGw3VFc_Q6wNDOrIKf91qZNEbO1f8k',
    appId: '1:695589450467:web:bd9c7572db0bfa2eb04bd6',
    messagingSenderId: '695589450467',
    projectId: 'application5s',
    authDomain: 'application5s.firebaseapp.com',
    databaseURL: 'https://application5s-default-rtdb.firebaseio.com',
    storageBucket: 'application5s.appspot.com',
    measurementId: 'G-90EHGWP1BW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHy9hjSeqksGqVqWjuPIEOwpPlwZ0an3c',
    appId: '1:695589450467:android:bdc77023bfcd6934b04bd6',
    messagingSenderId: '695589450467',
    projectId: 'application5s',
    databaseURL: 'https://application5s-default-rtdb.firebaseio.com',
    storageBucket: 'application5s.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbXhD8VOe7Kk9nDXxxwehd_i8yzdcBGtE',
    appId: '1:695589450467:ios:3c193c54fbd95998b04bd6',
    messagingSenderId: '695589450467',
    projectId: 'application5s',
    databaseURL: 'https://application5s-default-rtdb.firebaseio.com',
    storageBucket: 'application5s.appspot.com',
    iosBundleId: 'com.example.application',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbXhD8VOe7Kk9nDXxxwehd_i8yzdcBGtE',
    appId: '1:695589450467:ios:3c193c54fbd95998b04bd6',
    messagingSenderId: '695589450467',
    projectId: 'application5s',
    databaseURL: 'https://application5s-default-rtdb.firebaseio.com',
    storageBucket: 'application5s.appspot.com',
    iosBundleId: 'com.example.application',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTTVGw3VFc_Q6wNDOrIKf91qZNEbO1f8k',
    appId: '1:695589450467:web:02df619e6b3b690cb04bd6',
    messagingSenderId: '695589450467',
    projectId: 'application5s',
    authDomain: 'application5s.firebaseapp.com',
    databaseURL: 'https://application5s-default-rtdb.firebaseio.com',
    storageBucket: 'application5s.appspot.com',
    measurementId: 'G-CTV54MJXF9',
  );
}
